//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGVE_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourEvent
    {
        public string TourName { get; set; }
        public string EventMonth { get; set; }
        public int EventDay { get; set; }
        public string EventYear { get; set; }
        public int Fee { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
